#!/usr/bin/env bash

if [ -f $PWD/mono.conf ]; then
  source $PWD/mono.conf
fi
MONO_FULL_NAME="MonoRepo Tool"
MONO_VERSION="0.0.1"
MONO_AUTHOR="GreenCape, Niels Braczek"
MONO_COPYRIGHT_YEAR="2021"
export MONO_PLUGIN_DIR=${MONO_PLUGIN_DIR:-/.local/share/monorepo}
export MONO_PREFIX=${MONO_PREFIX:-"packages/"}

# Needed to enable parsing of strings returned by commands
export LANG=en_US.UTF-8

hello () {
  echo "$MONO_FULL_NAME $MONO_VERSION by $MONO_AUTHOR"
  echo ""
}

version () {
  echo "$MONO_FULL_NAME $MONO_VERSION"
  echo "(C)$MONO_COPYRIGHT_YEAR $MONO_AUTHOR"
}

usage () {
  hello
  cat <<EOT
Usage: mono [-h|--help] [-v|--version]
   or: mono <command> [<arguments>]

'mono help -a' and 'mono help -g' list available commands and some
instructions on mono concepts respectively. Use 'mono help <command>'
or 'mono help <concept>' to learn more about a specific command or concept.
EOT
}

source "$MONO_PLUGIN_DIR"/mono_commons

case $1 in
  -h | --help)
    usage
    exit 0
    ;;
  -v | --version)
    version
    exit 0
    ;;
  *)
    export MONO_COMMAND=$1
    ;;
esac

MONO_PLUGIN_FILE="$MONO_PLUGIN_DIR/mono-$MONO_COMMAND"

if [ ! -f "$MONO_PLUGIN_FILE" ]; then
  # Plugin does not exist
  echo "mono: '$MONO_COMMAND' is not a mono command. See 'mono --help'.";
  exit 1
fi

shift
"$MONO_PLUGIN_FILE" $@
