#!/usr/bin/env php

<?php
function usage()
{
    echo <<<EOT
Usage: mono composer <command>
   or: mono composer -h|--help

Arguments:

    <command>  The subcommand to be executed.

Options:

  -h|--help              Show this help text.

EOT;
}

$args       = $_SERVER['argv'];
$command    = preg_replace('~^.*?/mono-~', '', array_shift($args));
$positional = [];
while (count($args) > 0) {
    $arg = array_shift($args);
    if (preg_match('~^(--?[^ =]+)(?:=(\S*))?$~', $arg, $match)) {
        switch ($match[1]) {
            case '-n':
            case '--name':
                $name = $match[2] ?? array_shift($args);
                break;
            case '--dev':
                $requireSection = 'require-dev';
                break;
            case '-x':
            case '--expand':
                $expand = true;
                break;
            case '-h':
            case '--help':
                usage();
                exit(0);
            default:
                echo "Unknown option »{$match[1]}«\n";
                usage();
                exit(1);
        }
    } else {
        $positional[] = $arg;
    }
}

$name           = $name ?? 'combined';
$requireSection = $requireSection ?? 'require';
$expand         = $expand ?? false;

# Get positional arguments
$subCommand = array_shift($positional) ?? 'help';

switch ($subCommand) {
    case 'help':
        usage();
        exit(1);
    case 'merge':
        cmdMerge();
        break;
    case 'require':
        cmdRequire($positional, $requireSection, $expand);
        break;
}

echo "$command: Done.\n\n";
exit(0);

function cmdRequire(array $arguments, string $section, bool $expand)
{
    // Optional package name can also include a version constraint, e.g. foo/bar or foo/bar:1.0.0 or foo/bar=1.0.0 or "foo/bar 1.0.0"
    if (preg_match('~^(.*?)[:=](.*)$~', $arguments[0], $match)) {
        $package           = $match[1];
        $versionConstraint = $match[2];
    } else {
        $package           = array_shift($arguments);
        $versionConstraint = array_shift($arguments) ?? '*';
    }

    echo "Requiring $package:$versionConstraint\n";

    foreach (getSubtrees() as $subtree) {
        $composerJson = $subtree['prefix'] . '/composer.json';
        if (!file_exists($composerJson)) {
            // No composer.json file, so nothing to do
            continue;
        }

        $localJson = json_decode(file_get_contents($composerJson), true, 512, JSON_THROW_ON_ERROR);

        if (isset($localJson[$section][$package])) {
            $old = $localJson[$section][$package];
            if ($expand) {
                $new = mergeConstraints($old, $versionConstraint);
                // echo "Updated {$localJson['name']}[$section] from $package:$old to $package:$new\n";
                $localJson[$section][$package] = $new;
            } else {
                // echo "Replaced $package:$old with $package:$versionConstraint in {$localJson['name']}[$section]\n";
                $localJson[$section][$package] = $versionConstraint;
            }
        } else {
            // echo "Added $package:$versionConstraint to {$localJson['name']}[$section]\n";
            $localJson[$section][$package] = $versionConstraint;
        }


        // Write to disk
        $jsonContent = str_replace('\\/', '/', json_encode($localJson, JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR));
        file_put_contents($composerJson, $jsonContent . "\n");
    }
}

/**
 * @return void
 * @throws \JsonException
 */
function cmdMerge(): void
{
    if (!file_exists('composer.json')) {
        echo "Creating global composer.json\n";
        $globalJson = [
            '_readme'      => [
                'This file defines the combined dependencies of your project and subprojects',
                "This file was @generated using 'mono composer merge'",
            ],
            'require'      => [],
            'require-dev'  => [],
            'autoload'     => [],
            'autoload-dev' => [],
        ];
    } else {
        echo "Updating global composer.json\n";
        $globalJson = json_decode(file_get_contents('composer.json'), true, 512, JSON_THROW_ON_ERROR);
    }

    foreach (getSubtrees() as $subtree) {
        $composerJson = $subtree['prefix'] . '/composer.json';
        if (!file_exists($composerJson)) {
            // No composer.json file, so nothing to do
            continue;
        }

        $localJson  = json_decode(file_get_contents($composerJson), true, 512, JSON_THROW_ON_ERROR);
        $globalJson = mergeSections($globalJson, $localJson, getSubtrees());
    }

    // Cleanup
    foreach ($globalJson['require'] as $dependency => $versionConstraint) {
        if (isset($globalJson['require-dev'][$dependency])) {
            $globalJson['require'][$dependency] = intersectConstraint(
                $globalJson['require'][$dependency],
                $globalJson['require-dev'][$dependency]
            );
            unset($globalJson['require-dev'][$dependency]);
        }
    }

    uksort(
        $globalJson['require'],
        'compareDependencies'
    );
    uksort(
        $globalJson['require-dev'],
        'compareDependencies'
    );
    if (isset($globalJson['conflict'])) {
        uksort(
            $globalJson['conflict'],
            'compareDependencies'
        );
    }

    // Write to disk
    $jsonContent = str_replace('\\/', '/', json_encode($globalJson, JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR));
    file_put_contents('composer.json', $jsonContent . "\n");
}

function getSubtrees()
{
    return array_reduce(array_unique(file('.git/subtrees')), static function ($result, $line) {
        [$remoteName, $prefix, $remoteUrl] = explode(' ', $line);
        $composerJson = $prefix . '/composer.json';
        if (!file_exists($composerJson)) {
            // No composer.json => nothing to do
            return $result;
        }
        $json                  = json_decode(
            file_get_contents($composerJson),
            true,
            512,
            JSON_THROW_ON_ERROR
        );
        $result[$json['name']] = [
            'name'   => $remoteName,
            'prefix' => $prefix,
            'url'    => $remoteUrl,
        ];

        return $result;
    },                  []);
}

function mergeSections(array $global, array $local, array $subtrees): array
{
    foreach (['require', 'require-dev'] as $section) {
        if (!isset($local[$section])) {
            // Nothing to do, section is not declared
            continue;
        }

        foreach ($local[$section] as $dependency => $versionConstraint) {
            if (isset($subtrees[$dependency])) {
                // This is a local dependency, nothing to do
                continue;
            }

            if (!isset($global[$section][$dependency])) {
                // Not in global json yet, so take this
                $global[$section][$dependency] = $versionConstraint;
            } else {
                // Compute common versions
                $global[$section][$dependency] = intersectConstraint(
                    $global[$section][$dependency],
                    $versionConstraint
                );
            }
        }
    }

    if (isset($local['suggest'])) {
        $global = mergeSuggestions($global, $local, $subtrees);
    }

    if (isset($local['conflict'])) {
        $global = mergeConflicts($global, $local, $subtrees);
    }

    foreach (['autoload', 'autoload-dev'] as $autoload) {
        if (!isset($local[$autoload])) {
            // Nothing to do, section is not declared
            continue;
        }
        foreach ($local[$autoload] as $method => $assignment) {
            switch ($method) {
                case 'psr-0':
                case 'psr-4':
                    foreach ($assignment as $namespace => $path) {
                        $global[$autoload][$method][$namespace] = $subtrees[$local['name']]['prefix'] . '/' . $path;
                    }
                    break;
                case 'files':
                    foreach ($assignment as $path) {
                        $global[$autoload][$method][] = $subtrees[$local['name']]['prefix'] . '/' . $path;
                    }
                    break;
                default:
                    echo "Unknown autoload method $method\n";
            }
        }
    }

    return $global;
}

function mergeSuggestions(array $global, array $local, array $subtrees): array
{
    foreach ($local['suggest'] as $dependency => $description) {
        if (isset($subtrees[$dependency])) {
            // This is a local dependency, nothing to do
            continue;
        }

        if (!isset($global['require-dev'][$dependency]) && !isset($global['require'][$dependency])) {
            // Not yet required, add to suggest
            if (!isset($global['suggest'][$dependency])) {
                $global['suggest'][$dependency] = [];
            } elseif (is_string($global['suggest'][$dependency])) {
                $global['suggest'][$dependency] = explode(' - ', $global['suggest'][$dependency]);
            }
            $global['suggest'][$dependency][] = $description;
        }
    }

    foreach ($global['suggest'] ?? [] as $dependency => $description) {
        $global['suggest'][$dependency] = implode(' - ', array_unique((array)$description));
    }

    return $global;
}

function mergeConflicts(array $global, array $local, array $subtrees): array
{
    foreach ($local['conflict'] as $dependency => $constraint) {
        if (isset($subtrees[$dependency])) {
            // This is a local dependency, nothing to do
            continue;
        }

        if (!isset($global['conflict'][$dependency])) {
            $global['conflict'][$dependency] = $constraint;
            continue;
        }
        $global['conflict'][$dependency] = mergeConstraints($global['conflict'][$dependency], $constraint);
    }

    return $global;
}

function mergeConstraints(string $constraint1, string $constraint2): string
{
    $ranges1 = constraintToRanges($constraint1);
    $ranges2 = constraintToRanges($constraint2);
    $ranges  = mergeAllRanges([...$ranges1, ...$ranges2]);

    return rangesToConstraint($ranges);
}

function intersectConstraint(string $constraint1, string $constraint2): string
{
    if (empty($constraint1) || empty($constraint2)) {
        // One of the ranges is empty, so intersection is empty
        return '';
    }

    $ranges1 = constraintToRanges($constraint1);
    $ranges2 = constraintToRanges($constraint2);
    $ranges  = [];
    foreach ($ranges1 as $range1) {
        foreach ($ranges2 as $range2) {
            $intersection = intersectRanges($range1, $range2);
            if ($intersection !== null) {
                $ranges[] = $intersection;
            }
        }
    }

    $ranges = mergeAllRanges($ranges);

    return rangesToConstraint($ranges);
}

function rangesToConstraint(array $ranges)
{
    usort($ranges, function ($a, $b) {
        return version_compare($a['lower'] ?? $a['exact'] ?? '0.0', $b['lower'] ?? $b['exact'] ?? '0.0');
    });

    $constraints = [];
    foreach ($ranges as $range) {
        if (isset($range['exact'])) {
            return $range['exact'];
        }

        [$lowerMajor, $lowerMinor, $lowerPatch] = explode('.', $range['lower']);
        [$upperMajor, $upperMinor, $upperPatch] = explode('.', $range['upper']);
        $stability = null;
        if (strpos($lowerPatch, '-') !== false) {
            [$lowerPatch, $stability] = explode('-', $lowerPatch);
        }

        if ($range['lower'] === '0.0.0' && $range['upper'] === '999.999.999') {
            $constraints[] = '*';
        } elseif ((int)$upperMajor - (int)$lowerMajor > 1 || ((int)$upperMajor - (int)$lowerMajor === 1 && $upperMinor !== '0')) {
            $major         = (int)$lowerMajor;
            $constraints[] = rangesToConstraint([
                                                    [
                                                        'lower' => $range['lower'],
                                                        'upper' => ($major + 1) . '.0.0',
                                                    ],
                                                    [
                                                        'lower' => ($major + 1) . '.0.0',
                                                        'upper' => $range['upper'],
                                                    ],
                                                ]);
        } elseif ((int)$upperMajor - (int)$lowerMajor === 1 && $upperMinor === '0' && $upperPatch === '0') {
            $constraint = "^$lowerMajor.$lowerMinor";
            if ($lowerPatch !== '0') {
                $constraint .= ".$lowerPatch";
            }
            if ($stability !== null) {
                $constraint .= "@$stability";
            }
            $constraints[] = $constraint;
        } elseif ($upperMajor === $lowerMajor) {
            $constraint = ">=$lowerMajor.$lowerMinor";
            if ($upperMinor === $lowerMinor) {
                $constraint .= ".$lowerPatch";
            }
            if ($stability !== null) {
                $constraint .= "@$stability";
            }
            $constraint .= ",<$upperMajor.$upperMinor";
            if ($upperPatch !== '0') {
                $constraint .= ".$upperPatch";
            }
            $constraints[] = $constraint;
        } elseif ($lowerMajor === '0' && $lowerMinor === '0' && $lowerPatch === '0') {
            if ($upperMajor === '999' && $upperMinor === '999' && $upperPatch === '999') {
                $constraint = "*";
            } else {
                $constraint = "<$upperMajor.$upperMinor";
                if ($upperPatch !== '0') {
                    $constraint .= ".$upperPatch";
                }
            }
            $constraints[] = $constraint;
        } else {
            echo "Don't know how to convert " . print_r($range, true);
        }
    }

    return implode('|', $constraints);
}

function mergeAllRanges(array $ranges): array
{
    $indices      = array_keys($ranges);
    $merged       = false;
    $mergedRanges = [];
    $remove       = [];

    while (count($indices) > 1) {
        $i = array_shift($indices);
        if (in_array($i, $remove, true)) {
            continue;
        }
        $range1 = $ranges[$i];
        foreach ($indices as $j) {
            if (in_array($i, $remove, true)) {
                continue;
            }
            $range2      = $ranges[$j];
            $mergedRange = mergeRanges($range1, $range2);
            if ($mergedRange !== null) {
                $mergedRanges[] = $mergedRange;
                $remove[]       = $i;
                $remove[]       = $j;
                $merged         = true;
            }
        }
    }

    if (!$merged) {
        return $ranges;
    }

    foreach ($ranges as $i => $range) {
        if (in_array($i, $remove, true)) {
            continue;
        }
        $mergedRanges[] = $range;
    }

    return mergeAllRanges($mergedRanges);
}

function isInRange($version, $range)
{
    return version_compare($range['lower'], $version, 'le') && version_compare($version, $range['upper'], 'lt');
}

function constraintToRanges(string $constraints): array
{
    $ranges = [];
    foreach (preg_split('~\s*\|\|?\s*~', $constraints) as $constraint) {
        if (preg_match(
            '~^(\D+)?(\d+)(?:\.(x|\d+))?(?:\.(x|\d+))?(?:[@-](.+))?$~',
            $constraint,
            $match,
            PREG_UNMATCHED_AS_NULL
        )) {
            array_shift($match);
            [$operator, $major, $minor, $patch, $stability] = [...$match, null, null, null];

            switch ($operator) {
                case '^':
                    $lowerBound = $major . '.' . ($minor ?? 0) . '.' . ($patch ?? 0);
                    if ($stability !== null) {
                        $lowerBound .= '-' . $stability;
                    }
                    if ($major !== 0) {
                        $upperBound = ($major + 1) . '.0.0';
                    } else {
                        $upperBound = $major . '.' . ($minor + 1) . '.0';
                    }
                    $ranges[] = ['lower' => $lowerBound, 'upper' => $upperBound];
                    break;
                case '~':
                    $lowerBound = $major . '.' . ($minor ?? 0) . '.' . ($patch ?? 0);
                    if ($stability !== null) {
                        $lowerBound .= '-' . $stability;
                    }
                    if ($patch === null) {
                        $upperBound = ($major + 1) . '.0.0';
                    } else {
                        $upperBound = $major . '.' . ($minor + 1) . '.0';
                    }
                    $ranges[] = ['lower' => $lowerBound, 'upper' => $upperBound];
                    break;
                case '>=':
                    $lowerBound = $major . '.' . ($minor ?? 0) . '.' . ($patch ?? 0);
                    if ($stability !== null) {
                        $lowerBound .= '-' . $stability;
                    }
                    $upperBound = '999.999.999';
                    $ranges[]   = ['lower' => $lowerBound, 'upper' => $upperBound];
                    break;
                case '<':
                    $lowerBound = '0.0.0';
                    $upperBound = $major . '.' . ($minor ?? 0) . '.' . ($patch ?? 0);
                    $ranges[]   = ['lower' => $lowerBound, 'upper' => $upperBound];
                    break;
                case null:
                    $lowerBound = '0.0.0';
                    $upperBound = '999.999.999';
                    $ranges[]   = ['lower' => $lowerBound, 'upper' => $upperBound];
                    break;
                default:
                    echo "Don't know how to handle $operator\n";
                    break;
            }
        } elseif (preg_match('~^(.+?)[ ,](.+?)$~', $constraint, $match)) {
            $range1   = constraintToRanges($match[1]);
            $range2   = constraintToRanges($match[2]);
            $ranges[] = intersectRanges($range1[0], $range2[0]);
        } elseif (empty($constraint) || $constraint === '*') {
            $ranges[] = ['lower' => '0.0.0', 'upper' => '999.999.999'];
        } else {
            echo "Don't know how to parse $constraint\n";
            $ranges[] = ['exact' => $constraint];
        }
    }

    return $ranges;
}

/**
 * @param  array  $range1
 * @param  array  $range2
 *
 * @return array|null
 */
function intersectRanges(array $range1, array $range2): ?array
{
    /** @todo Check containment; for now, this works */
    if (isset($range1['exact'])) {
        return $range1;
    }
    if (isset($range2['exact'])) {
        return $range2;
    }

    $lowerBound = version_compare($range1['lower'], $range2['lower'], 'lt') ? $range2['lower'] : $range1['lower'];
    if (preg_match('~(-.*)$~', $lowerBound, $match)) {
        $lowerBound = str_replace($match[1], '', $lowerBound);
    }
    $upperBound = version_compare($range1['upper'], $range2['upper'], 'lt') ? $range1['upper'] : $range2['upper'];

    if (version_compare($lowerBound, $upperBound, 'ge')) {
        return null;
    }

    return ['lower' => $lowerBound . ($match[1] ?? ''), 'upper' => $upperBound];
}

/**
 * @param  array  $range1
 * @param  array  $range2
 *
 * @return array|null
 */
function mergeRanges(array $range1, array $range2): ?array
{
    if (isInRange($range2['lower'], $range1) || isInRange($range2['upper'], $range1)) {
        $lowerBound = version_compare($range1['lower'], $range2['lower'], 'lt') ? $range1['lower'] : $range2['lower'];
        $upperBound = version_compare($range1['upper'], $range2['upper'], 'lt') ? $range2['upper'] : $range1['upper'];

        return ['lower' => $lowerBound, 'upper' => $upperBound];
    }

    return null;
}

function compareDependencies($a, $b)
{
    $priorities = [
        '~^php$~' => 0,
        '~^ext-~' => 1,
        '~^psr/~' => 2,
        '~.*~'    => 3,
    ];
    foreach ($priorities as $pattern => $priority) {
        if (preg_match($pattern, $a)) {
            $prioA = $priority;
            break;
        }
    }
    foreach ($priorities as $pattern => $priority) {
        if (preg_match($pattern, $b)) {
            $prioB = $priority;
            break;
        }
    }
    if ($prioA === $prioB) {
        return $a <=> $b;
    }

    return $prioA <=> $prioB;
}

function dumpRange($range)
{
    return "[{$range['lower']}-{$range['upper']}]";
}

function dumpRanges($ranges)
{
    return implode(
        ', ',
        array_reduce($ranges, function ($result, $range) {
            $result[] = dumpRange($range);

            return $result;
        },           [])
    );
}
